org: vinitvictor
app: aws-python-flask-api

# serverless.yml

service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: false

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-west-2
  iam:
    role:
      statements:
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::*/*'
        # Allow functions to read/write objects in a ddb
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - 'arn:aws:dynamodb:us-west-2:015041540109:table/file_and_content'
        # Allow invoke lambda
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource:
            - 'arn:aws:lambda:us-west-2:015041540109:function:convert-file-to-csv-and-upload-it-to-s3'


functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
